apiVersion: federation.symphony/v1
kind: CatalogContainer
metadata:
  name: line-config
spec:  
---
apiVersion: federation.symphony/v1
kind: Catalog
metadata:
  name: line-config-v-v1
spec:
  rootResource: line-config
  catalogType: config
  properties:
    EXTRA-LINE: # Added due to config behavior described in bug: https://github.com/eclipse-symphony/symphony/issues/202
      line1: ${{$if($config('line1:v1', 'IS_PREMIUM_LINE'), $config('premiumproperties:v1',''), '')}}
      line2: ${{$if($config('line2:v1', 'IS_PREMIUM_LINE'), $config('premiumproperties:v1',''), '')}}
