apiVersion: apps/v1
kind: Deployment
metadata:
  name: symphony-api
  labels:
    app: symphony-api
  namespace: symphony-k8s-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: symphony-api
  template:
    metadata:
      labels:
        app: symphony-api
    spec:
      {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
      {{- end }}
      containers:
      - name: symphony-api
        securityContext: {{- toYaml .Values.securityContext | nindent 12 }}
        image: {{ .Values.paiImage.repository }}:{{ .Values.paiImage.tag }}
        ports:
        - containerPort: 8080
        - containerPort: 8081
        env:          
          - name: "CUSTOM_VISION_KEY"
            valueFrom:
              secretKeyRef:
                key:  CUSTOM_VISION_KEY
                name: {{ .Release.Name }}-auth
      serviceAccountName: pai-sp