fullnameOverride: symphony
symphonyImage:
  repository: symphonycr.azurecr.io/symphony-k8s
  pullPolicy: IfNotPresent
  tag: "latest"
paiImage:
  repository: symphonycr.azurecr.io/symphony-api
  pullPolicy: IfNotPresent
  tag: "latest"
CUSTOM_VISION_KEY: "AAAA"
installServiceExt: false
global:
  azure:
    identity:
      enabled: false
observability:
  tracing:
    exporter:
      zipkin: true
zipkin:
  fullnameOverride: symphony-zipkin
cert-manager:
  fullnameOverride: symphony-cert-manager
