apiVersion: solution.symphony/v1
kind: Solution
metadata: 
  name: sample-staged-solution-v-version1
spec:
  rootResource: sample-staged-solution
  components:
  - name: staged-component
    type: container
    properties:
      foo: "bar"
      