apiVersion: federation.symphony/v1
kind: Catalog
metadata:
  name: sample-config
spec:  
  siteId: hq
  type: config
  metadata:
    schema: sample-schema
  properties:
    foo: "foo@hotmail.com"
    bar: "15"